CREATE TABLE nomis_sync_payloads (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     transaction_id INTEGER,
                                     request_id VARCHAR(36),
                                     caseload_id VARCHAR(255),
                                     request_type_identifier VARCHAR(255),
                                     body CLOB NOT NULL
);

CREATE INDEX idx_nomis_sync_payloads_timestamp ON nomis_sync_payloads (timestamp);
CREATE INDEX idx_nomis_sync_payloads_request_type ON nomis_sync_payloads (request_type_identifier);
CREATE INDEX idx_nomis_sync_payloads_transaction_id ON nomis_sync_payloads (transaction_id);
CREATE INDEX idx_nomis_sync_payloads_request_id ON nomis_sync_payloads (request_id);
CREATE INDEX idx_nomis_sync_payloads_caseload_id ON nomis_sync_payloads (caseload_id);