package uk.gov.justice.digital.hmpps.prisonerfinancepocapi.models.sync

import io.swagger.v3.oas.annotations.media.Schema
import java.util.UUID

@Schema(description = "Receipt details for a general ledger balance synchronization request, indicating the overall outcome of the batch operation.")
data class SyncGeneralLedgerBalanceReceipt(
  @Schema(
    description = "The unique identifier of the original synchronization request. This UUID was provided by the client as the idempotency key for this batch operation.",
    example = "a1b2c3d4-e5f6-7890-1234-567890abcdef",
    required = true,
  )
  val requestId: UUID,

  @Schema(
    description = "The unique UUID generated by the **finance system** for this synchronized general ledger balance batch.",
    example = "f1e2d3c4-b5a6-9876-5432-10fedcba9876",
    required = true,
  )
  val id: UUID,
  @Schema(
    description = "The overall action taken on the general ledger balances.",
    example = "CREATED",
    required = true,
  )
  var action: Action,
) {
  @Schema(description = "The outcome of processing the general ledger balance synchronization request.")
  enum class Action {
    @Schema(description = "A new batch of general ledger balances was successfully processed and recorded. This implies new entries or a full overwrite.")
    CREATED,

    @Schema(description = "An existing batch of general ledger balances was successfully updated or processed with no new creations. This implies partial updates or reconciliation.")
    UPDATED,
  }
}
